---

.getimagetag:
  stage: build
  image:
    name: alpine:3.16.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        APP_VERSION_POSTFIX: "-mr${CI_MERGE_REQUEST_IID}"
    - if: '$CI_COMMIT_TAG'
      variables:
        APP_VERSION_POSTFIX: ""
    - when: always
      variables:
        APP_VERSION_POSTFIX: "-${CI_PIPELINE_ID}"
  script:
    - echo IMAGE_TAG=${APP_VERSION}${APP_VERSION_POSTFIX} > .env
  artifacts:
    reports:
      dotenv: .env

.build:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --cache=true
      --cache-ttl 720h
      --cache-repo "${CI_REGISTRY_USER}/${PROJECT_NAME}"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${APP_DOCKERFILE}"
      --destination "${CI_REGISTRY_USER}/${PROJECT_NAME}:$IMAGE_TAG"
      --ignore-path=/product_uuid
  needs:
    - .getimagetag
